# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerStat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PlayerStat.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10PlayerStat.proto\"F\n\x0ePlayerKillStat\x12\r\n\x05kills\x18\x01 \x02(\x05\x12\x13\n\x0bkills_place\x18\x02 \x02(\x05\x12\x10\n\x08nickname\x18\x03 \x02(\t\"Y\n\x11PlayerSurviveStat\x12\x15\n\rtime_survived\x18\x01 \x02(\x05\x12\x1b\n\x13time_survived_place\x18\x02 \x02(\x05\x12\x10\n\x08nickname\x18\x03 \x02(\t\"\xbc\x01\n\x08RankInfo\x12!\n\x08top5kill\x18\x01 \x03(\x0b\x32\x0f.PlayerKillStat\x12#\n\nround5kill\x18\x02 \x03(\x0b\x32\x0f.PlayerKillStat\x12\'\n\x0btop5survive\x18\x03 \x03(\x0b\x32\x12.PlayerSurviveStat\x12)\n\rround5survive\x18\x04 \x03(\x0b\x32\x12.PlayerSurviveStat\x12\x14\n\x0conline_count\x18\x05 \x02(\x05\"`\n\nPlayerInfo\x12\r\n\x05kills\x18\x01 \x02(\x05\x12\x15\n\rtime_survived\x18\x02 \x02(\x05\x12\x10\n\x08nickname\x18\x03 \x02(\t\x12\x0c\n\x04hash\x18\x04 \x02(\x05\x12\x0c\n\x04live\x18\x05 \x02(\x08')
)




_PLAYERKILLSTAT = _descriptor.Descriptor(
  name='PlayerKillStat',
  full_name='PlayerKillStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kills', full_name='PlayerKillStat.kills', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kills_place', full_name='PlayerKillStat.kills_place', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='PlayerKillStat.nickname', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=90,
)


_PLAYERSURVIVESTAT = _descriptor.Descriptor(
  name='PlayerSurviveStat',
  full_name='PlayerSurviveStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_survived', full_name='PlayerSurviveStat.time_survived', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_survived_place', full_name='PlayerSurviveStat.time_survived_place', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='PlayerSurviveStat.nickname', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=181,
)


_RANKINFO = _descriptor.Descriptor(
  name='RankInfo',
  full_name='RankInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='top5kill', full_name='RankInfo.top5kill', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round5kill', full_name='RankInfo.round5kill', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top5survive', full_name='RankInfo.top5survive', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round5survive', full_name='RankInfo.round5survive', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='online_count', full_name='RankInfo.online_count', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=372,
)


_PLAYERINFO = _descriptor.Descriptor(
  name='PlayerInfo',
  full_name='PlayerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kills', full_name='PlayerInfo.kills', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_survived', full_name='PlayerInfo.time_survived', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nickname', full_name='PlayerInfo.nickname', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hash', full_name='PlayerInfo.hash', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='live', full_name='PlayerInfo.live', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=470,
)

_RANKINFO.fields_by_name['top5kill'].message_type = _PLAYERKILLSTAT
_RANKINFO.fields_by_name['round5kill'].message_type = _PLAYERKILLSTAT
_RANKINFO.fields_by_name['top5survive'].message_type = _PLAYERSURVIVESTAT
_RANKINFO.fields_by_name['round5survive'].message_type = _PLAYERSURVIVESTAT
DESCRIPTOR.message_types_by_name['PlayerKillStat'] = _PLAYERKILLSTAT
DESCRIPTOR.message_types_by_name['PlayerSurviveStat'] = _PLAYERSURVIVESTAT
DESCRIPTOR.message_types_by_name['RankInfo'] = _RANKINFO
DESCRIPTOR.message_types_by_name['PlayerInfo'] = _PLAYERINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerKillStat = _reflection.GeneratedProtocolMessageType('PlayerKillStat', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERKILLSTAT,
  '__module__' : 'PlayerStat_pb2'
  # @@protoc_insertion_point(class_scope:PlayerKillStat)
  })
_sym_db.RegisterMessage(PlayerKillStat)

PlayerSurviveStat = _reflection.GeneratedProtocolMessageType('PlayerSurviveStat', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERSURVIVESTAT,
  '__module__' : 'PlayerStat_pb2'
  # @@protoc_insertion_point(class_scope:PlayerSurviveStat)
  })
_sym_db.RegisterMessage(PlayerSurviveStat)

RankInfo = _reflection.GeneratedProtocolMessageType('RankInfo', (_message.Message,), {
  'DESCRIPTOR' : _RANKINFO,
  '__module__' : 'PlayerStat_pb2'
  # @@protoc_insertion_point(class_scope:RankInfo)
  })
_sym_db.RegisterMessage(RankInfo)

PlayerInfo = _reflection.GeneratedProtocolMessageType('PlayerInfo', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERINFO,
  '__module__' : 'PlayerStat_pb2'
  # @@protoc_insertion_point(class_scope:PlayerInfo)
  })
_sym_db.RegisterMessage(PlayerInfo)


# @@protoc_insertion_point(module_scope)
